# Generated by Django 3.1.4 on 2020-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201220_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='smtpport',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
